#
# \brief  Seoul on Genode - test to boot from a raw disk
# \author Alexander Boettcher
# \date   2013-06-11
#
# This run script starts the Seoul VMM booting from a disc image.
# It assumes that the module files are present at '<build-dir>/bin/'
#

set use_multiboot     0
set use_genode_iso    0
set use_model_ahci    1
set use_model_ide     0

set use_block_vdi     0
set use_block_ram     0
set use_block_sata    1

set partition_raw     1

set use_part_raw      2
set use_part_block    0

set use_nic_session   1

set use_top           1

set memory_vmm_vm     "8144M"

set vcpus_to_be_used  2

set use_virtio        0

set cpuid_native      "yes"

set use_disk_count    3

if {[have_include power_on/qemu]} {

	set image  "seoul-disc.raw"
	set image2 "seoul-disc2.raw"
	set image3 "seoul-disc3.raw"

	if {![file exists bin/$image]} {
		puts "Please provide a disk image file to  bin/$image"
		exit 1
	}

	append qemu_args " -m 10200 "
#	append qemu_args " -cpu EPYC"
	append qemu_args " -accel kvm -cpu host"
	append qemu_args " -smp $vcpus_to_be_used"

	if { $use_block_sata && $use_disk_count > 1 } {
		if {![file exists bin/$image2]} {
			catch { exec dd if=/dev/zero of=bin/$image2 bs=1M count=130 }

			if { $use_part_block } {
				exec sgdisk bin/$image2
				exec sgdisk --new 1:002048:133119 bin/$image2
				exec sgdisk --new 2:133120:264191 bin/$image2
				exec sgdisk -p bin/$image2
			}
		}

		if {![file exists bin/$image3]} {
			if { $use_disk_count > 2 } {
				catch { exec dd if=/dev/zero of=bin/$image3 bs=1M count=130 }
			}
		}
	}

	append_if [have_include image/iso] qemu_args " -boot d "
}

source ${genode_dir}/repos/world/run/seoul.inc

run_genode_until forever
